    create table "movie" (
        "id" bigint generated by default as identity,
        "title" varchar(255),
        "winner" boolean,
        "year" integer not null,
        primary key ("id")
    );

    create table "producer" (
        "id" bigint generated by default as identity,
        "name" varchar(255),
        primary key ("id")
    );

    create table "studio" (
        "id" bigint generated by default as identity,
        "name" varchar(255),
        primary key ("id")
    );

    create table "movie_producers" (
        "movie_id" bigint not null,
        "producers_id" bigint not null
    );

    create table "movie_studios" (
        "movie_id" bigint not null,
        "studios_id" bigint not null
    );

   alter table if exists "movie_producers"
       add constraint "FKmovie_producers_producer"
       foreign key ("producers_id")
       references "producer";


   alter table if exists "movie_producers"
       add constraint "FKmovie_producers_movie"
       foreign key ("movie_id")
       references "movie";

   alter table if exists "movie_studios"
       add constraint "FKmovie_studios_studio"
       foreign key ("studios_id")
       references "studio";

    alter table if exists "movie_studios"
       add constraint "FKmovie_studios_movie"
       foreign key ("movie_id")
       references "movie";